### ISSUE TITLE
additional AI models and a feature request.

### ISSUE THREAD

**Issue by science64** [EliasPereirah/OrionChat#1]
This is not a issue per se.

can you please add deepinfra, together ai and openrouter? and is there any functionality to add models from the UI?

thanks this looks great app.

**Comment by EliasPereirah** [comment]
Thank you for opening this issue and for the positive feedback about the app!

### Regarding the addition of new models (deepinfra, together AI, and openrouter):

The inclusion of deepinfra, together AI, and openrouter seems interesting, and I will be investigating the feasibility and potential for integration this week. I will keep you updated here.

## Regarding adding models through the UI:

Currently, the functionality to add models directly through the user interface (UI) is not available. I acknowledge that this is a very important feature and will look into enabling users to add via UI soon.

Thank you again for the suggestion, and if you have any more ideas or questions, feel free to share!

**Comment by EliasPereirah** [comment]
Thanks Süleyman for the suggestion.
Done.
Note: Some features may not be available, such as Image generation.
