### ISSUE TITLE
copy button is not working and file upload only works with image

### ISSUE THREAD

**Issue by science64** [EliasPereirah/OrionChat#2]
Hello again,

I am using your nice app regularly now. So I have a couple of feedback an update request.

- copy button is not working somehow, meaning that copy button doest copy the text or code into clipboard.
- Second of all I tried to upload pdf, txt, .md, .py files in the upload sessions but I am getting error, when I try to upload image it is working.
- Lastly , could you please add shortcut for clearing or deleting the current chat (like shift+del or cntr+del).

copy button part error: 
![image](https://github.com/user-attachments/assets/3b3c0cf4-8be9-4fbe-a8b5-17f6f5199129)

I got this error
```
script.js?v=2.4.1:778 Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at HTMLButtonElement.<anonymous> (script.js?v=2.4.1:778:37)
(anonymous)	@	script.js?v=2.4.1:778
script.js?v=2.4.1:726 Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at HTMLButtonElement.<anonymous> (script.js?v=2.4.1:726:37)
(anonymous)	@	script.js?v=2.4.1:726
```

this is when I upload .py file for asking the about the code (to meta llama 3.1 from cebras)
![image](https://github.com/user-attachments/assets/d4f78a96-e51e-4753-949f-8111b3def857)

**Comment by science64** [comment]
For the copy part, I fixed it because of localhost; I followed this ==> 

Chrome: You can enable the "Insecure origins treated as secure" flag in Chrome for specific URLs like http://localhost:8000.
Go to chrome://flags/ in your Chrome browser.
Search for "Insecure origins treated as secure."
Add http://localhost:8000 (or your application's URL) to the list of allowed origins.
Restart Chrome.

**Comment by EliasPereirah** [comment]
> Hello again,
> 
> I am using your nice app regularly now. So I have a couple of feedback an update request.
> 
> * copy button is not working somehow, meaning that copy button doest copy the text or code into clipboard.
> * Second of all I tried to upload pdf, txt, .md, .py files in the upload sessions but I am getting error, when I try to upload image it is working.
> * Lastly , could you please add shortcut for clearing or deleting the current chat (like shift+del or cntr+del).
> 
> copy button part error: ![image](https://private-user-images.githubusercontent.com/17804087/397149569-3b3c0cf4-8be9-4fbe-a8b5-17f6f5199129.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1Njc0MTIsIm5iZiI6MTczNDU2NzExMiwicGF0aCI6Ii8xNzgwNDA4Ny8zOTcxNDk1NjktM2IzYzBjZjQtOGJlOS00ZmJlLWE4YjUtMTdmNmY1MTk5MTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDAwMTE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkM2Q1OWY5ODFhNmM2Y2Q1YzkzNjQwZmVmNTkyMWQ5M2U4NTdiMmJmZGJjNGM2MmM0NGJhZDI4YTMyZTBjZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8KLmL5Nm-hWP8Z5_DrWPdJ6VI_7kDRQH6D0PSs_qN0g)
> 
> I got this error
> 
> ```
> script.js?v=2.4.1:778 Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
>     at HTMLButtonElement.<anonymous> (script.js?v=2.4.1:778:37)
> (anonymous)	@	script.js?v=2.4.1:778
> script.js?v=2.4.1:726 Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
>     at HTMLButtonElement.<anonymous> (script.js?v=2.4.1:726:37)
> (anonymous)	@	script.js?v=2.4.1:726
> ```
> 
> this is when I upload .py file for asking the about the code (to meta llama 3.1 from cebras) ![image](https://private-user-images.githubusercontent.com/17804087/397149685-d4f78a96-e51e-4753-949f-8111b3def857.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1Njc0MTIsIm5iZiI6MTczNDU2NzExMiwicGF0aCI6Ii8xNzgwNDA4Ny8zOTcxNDk2ODUtZDRmNzhhOTYtZTUxZS00NzUzLTk0OWYtODExMWIzZGVmODU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE5VDAwMTE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiODM4MTU1MDJlNDY1NGQwZjBjZjRkYmQwZTVmMzkzN2E1Njg3MjM0ZWM3ZWU2ZTNhMmRiZTY5NmI0ZDdkNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mgJOjCZl_LeTbl7jYG6k7NTfVz4muKox-Toy5ztZA00)

Hello Süleyman, thank you for the contribution and feedback, this will help make this interface even better.

I will check what can be done to enable the upload of other file types besides images.

Currently, only Google Gemini has the option to upload video, audio, pdf, and txt implemented; most other models do not accept these other formats. However, it is possible to convert the content to text and send the text instead of the file. I will check the possibility of implementing this soon.

You can use the shortcut `Ctrl + Q´  to start a new chat without deleting the current one, and I have just implemented `Ctrl + Del` as suggested, which deletes the current chat.

**Comment by EliasPereirah** [comment]
That's it. You can now send files other than images.
PDF is still only possible with Google Gemini.
Have a great day!
