### ISSUE TITLE
How to Run

### ISSUE THREAD

**Issue by arjunrockzz07** [EliasPereirah/OrionChat#3]
Bro can you make some improvements, use Superbase DB and add steps how to run in local, and also is posssible docker file and docker compose file. this make your project easy for non-techinical-guys to use it

**Comment by EliasPereirah** [comment]
Hi Arjun Reddy.

This project is almost entirely in pure JavaScript, so you can download it and use it without even having to set up a server.

However, there are some features that you will need to have an active server with PHP if you want to use them. These features are proxying and getting subtitles from YouTube.

Download the zip: https://github.com/EliasPereirah/OrionChat/archive/refs/heads/master.zip

If you prefer, use it via GitHub Pages https://eliaspereirah.github.io/OrionChat/

How do you think using Supabase can be useful? Do you have any example of a use case that justifies this need?

I will check about the possibility of adding docker file, it seems like a great idea.
Any other ideas or suggestions are welcome, thank you.
